
title: Sanghyu Yoon
description: Personal Page
# For user sites (username.github.io), leave baseurl empty
baseurl: ""
url: "https://yoonsanghyu.github.io"
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
kramdown:
  input: GFM
